import numpy as np
# n=np.random.rand(3)
# print(n)
import matplotlib.pyplot as plt
# snum=np.random.standard_normal(2000)
# plt.hist(snum,bins=25)
# plt.show()
# x=np.linspace(0,20,10)
# print(x)
# y1=np.sin(x)
# y2=np.cos(x)
# plt.plot(x,y1,label="sine")
# plt.plot(x,y2,label="cos")
# plt.legend(loc="right")
# plt.show()
num=np.fromfile("C:/data/numbers.txt",dtype=int,sep=",")
items=np.genfromtxt("C:/data/items.txt",dtype='str',delimiter=",")
x=np.arange(len(items))
plt.bar(x,num)
plt.xticks(x,items)
plt.show()